const IOTA = require('iota.lib.js');
const CCurl = require('ccurl.interface.js');
const {
    promisify
} = require('util');

// not really used as we don't do any TX with value changes.
const MWM = 15;
let seed = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ9ABCDEFGHIJKLMNOPQRSTUVWXYZ9ABCDEFGHIJKLMNOPQRSTUVWXYZ9';
let targetAddress = '99999999999999999999999999999999999999999999999999999999999999999RUUVI9LOVES9IOTA';
let targetTag = 'ALL9THE9TAGGING9YOULL9NEED9';
let message = 'HSVKSZBJFAI9OUUXZSAYVPHENMYSMDOTXSVUISVGWN9DVUBYTNXCFQK9AAAWHFIBHLPRHXIXPX9HUCRUCILCKVZGYBOJEHGJFA9YFGIHNS99ILCOOKWV9FVLGVKCMPVPDZFXTKOBGVKXVTDLOVYCEYTTGRXVWBVFKFXHWQGQSQNESOEAMSSVBCOQVCWKEHHONFQKIBEHXYBNYIYBBXFZNBLGVHXPJTPSRB9FSVGBNVHADGGLKLIIARULVV9ALN99QTS9JUGTTFCNCXEGUZIUFWMXGYVK9YDKFVXMHDRNHRINXKKCIELUAGIDFUIANFNMSZQJGDYDZDQDURRLXHLYCDLFBRZYTQDJZUVAWXKWHGJHDUHETGNDSP9ABBIU9PAGZMLJKNCXTCZSQJXRBCEJ9PQPFLYKLUMEUGNOOTUFLABBBAPEWTWKTAMLMARRLSYRCWSYZRITTRLLLBP9XTRCFMJYYIZSZEVSXTVBFLAOENMPPKWZOUEBIORBVIWXVCTNKRYJMAXTKKMUR9IJDWEVHUBUJMQZIMAFSGZAIGHWHMOOLLINHNVJSIAEDUAO9ZZRABQ9AFRMEE9GLXHSMZIVZIZSSPHTYDKBFAMCWOPOEMFBJOJBPOVQCMUFPXHKQKQXPJKDTK9SK9LNGWYHCEZTBZWQDRCS9XKYHNXWSPHLEQSP9EODYIVQUJROCJWCPVDYJLZUGENRCUGKCLKALLQNGEVCGGNYZKHSZXADXABVRKJBGLHE9KRBSHODGRWQEGJZDL9OTITSAOUJSOGQYJRNIBCYWVZQTPAKULCGTYYHFPNHANGUR9IFY9SOKLMFWYZFEWZOEUXSU9JLXNWZ9ZPOGBQVWRBUQZVOAADABGWYLGSVIKEJBVARTCOUDOBFBFHSY9WNRYBHLGCAQKNZQNDYQMKOGECWIUVWIZ9ON9VFCLMODZELBZQGHLHWZRMDZXROMRWVAXUKCKVFU9AVTLKROICXLDBSPLCJGMXXTXTWLNIBQEQXWTNLABO9EWESSKZCAEQONSABZOCQJOYANPRVXBVYYUUNWAEHGRITYVZPDEMPQKRIRBQMHYHWXQXTXIUFPRJJRIORNUPFIIKVM9QOQVTLGXIRATSYXELMUAJNLLPMPCVSGJEEONRROUWWBBXC9XIHCOOMHYJHPYVXBRKAWB9KNZDUS9HEFLFSSWPPMFKROKJTXVFFLYJZRSJLCHYCDPEPNHDP9TBZGOPRKDLTNZRALWLIWKH9MSRVIFWLTDMNICQRW9HIQPQBG9WZZLCDOZYIDUSEIPEUGJ9ARCVNQZFVQRRUVPMQYQELADHDQFMBTRXDARMGHOQIJMGKJKGNMZAIGCTIP9VWLVOQVZHWDCOXOWLJHWKMELANENMMLYKL9Y9CI9QAOHHJSZBLAAIOPGQVPXLH9AZUUIWSMMNORKBNDSJVBCQLNMQN9E9QKAWIQUCFTVUEJKQKYDFXJZXGKQJXFD9XZUZZDSNVGJBYXCSWHDDDFIEHUXW9F9XQMOV9TVAPYHPLRNOBNWSIPJ9OLFZTAQEHXVAOYOVPBHYTMRNKVHDFZPAFRJEBZUXDPKSKJCBKLRYEWQUJSDJWEX9UJRRFHKE9AHBBNTTFIIIBHRFJVOMOEGB9VWZED9WADAPKFEAFVV99CAHRXD9RXRJDAULFRTKJLLTB9KRLCOM99BTBKDXMXRJOZSYXLSXDQQDEZ9NPCBJDVHARHHJCPGZTMJAV9PJSAEX9YILZBKUVAVNGFRWETNNFMRJYFXSOAOT9KDXTHAWABGZLWYLZVGABLSWUQGLAVWOFUAVQNAGLQWLGXCUSYXTWWCFWDHERSNXGFHKOEXWMBXBYASSBZGNVBOOPAWYBLDQMBXVBVARTDQPYCZLKWIVVJFLVINRDIIKLGEDWSLMOVLSYGDWZIAYRUPKJATMWBTJUADLJUJXI9XVXF9VXWGIIMEIESHZSCGUNAZBJFUXYJQ9KMBZVGJCOWOXGMTA9V9HI9FXILRKYQIFIGAGGCMYAQU9WKIHSOKKRFMWQZBGHHX9UARCSZJGLNGNMRNVBYMGXVRCSLRKMBWIWJVVWAHKAFQPJWOOMKQDOIKONZXKPZ9FXPNZUVT9ZVIQCBRECOQRZJPPYWQAPEWNVMSS9BPPOXCSOZFGP9NNRLQWEJWBKRXRDJAUGUCLZIVYYIPEH9YHR9VGNLFLTJQVYWXHVFKFFPANVMMKNUNUUFDLAVPQNNSGFGKID9CUQVMWWPBAWN9SPSTFDGUSYSCWTNCMNVPPJFITVKTAIQNHWPOKXCTJGTMPPFFBUIQIHPSOYPPZXLUKKCSGFQLRJLR9GOZIALKBIJOLTKDOTBHUSGMYM9WRPBUK9GIIJKWNTJLPDAXZYCKGLCRLRSVHTYYJNHOQEUVRFDRNJISJEEPAJANACSFPDOHGVNCSSGXAAHS9CYDYQBZOQZCFDOHBFDEVGAIF';

// sample MAM payload.

// construct iota.lib.js instance
let iota = new IOTA({
    'host': 'http://service.iotasupport.com',
    'port': 14265
});

const PCCurl = promisify(CCurl);
const PprepareTransfers = promisify(iota.api.prepareTransfers);
const PgetTransactionsToApprove = async depth => {
    return new Promise((resolve, reject) => {
        iota.api.getTransactionsToApprove(depth, function(err, suc) {
            if (err != undefined) {
                reject(err);
            } else {
                resolve(suc);
            }
        });
    });
};

const PbroadcastTransactions = async trytes => {
  return new Promise((resolve, reject) => {
    iota.api.broadcastTransactions(trytes, function(err, suc) {
      if (err != undefined) {
        reject(err);
      } else {
        resolve(suc);
      }
    });
  });
};

PprepareTransfers(seed, [{
        address: targetAddress,
        value: 0,
        message: message,
        tag: targetTag
    }]).then(transactions => {
        return PgetTransactionsToApprove(5).then(toApprove => {
            return PCCurl(toApprove.trunkTransaction, toApprove.branchTransaction, MWM, transactions);
        });
    }).then(bundle => PbroadcastTransactions(bundle))
    .then(ret => console.log(ret));
